# Generated by Django 3.0.6 on 2020-10-01 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0002_auto_20200930_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, '正在进行'), (2, '完成'), (3, '关闭')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='结束时间')),
                ('outcome', models.CharField(default=' ', max_length=255, verbose_name='产出')),
            ],
            options={
                'verbose_name': '事件',
                'verbose_name_plural': '事件',
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': '计划', 'verbose_name_plural': '计划'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '任务', 'verbose_name_plural': '任务'},
        ),
        migrations.AlterField(
            model_name='project',
            name='comment',
            field=models.CharField(default=' ', max_length=255, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='project',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default=' ', max_length=30, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='归属'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, '正在进行'), (2, '完成'), (3, '关闭')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.IntegerField(choices=[(1, '学习'), (2, '工作'), (3, '生活'), (4, '其他')], default=4, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='comment',
            field=models.CharField(default=' ', max_length=255, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='计划结束'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='keyword',
            field=models.CharField(default=' ', max_length=30, verbose_name='关键字'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='计划开始'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.IntegerField(choices=[(1, '正在进行'), (2, '完成'), (3, '关闭')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(default=' ', max_length=255, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='task',
            name='keyword',
            field=models.CharField(default=' ', max_length=30, verbose_name='关键字'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todo.Project', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, '正在进行'), (2, '完成'), (3, '关闭')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='task',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.DeleteModel(
            name='Step',
        ),
        migrations.AddField(
            model_name='action',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='todo.Schedule', verbose_name='预约表'),
        ),
        migrations.AddField(
            model_name='action',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='todo.Task', verbose_name='针对任务'),
        ),
    ]
