# Generated by Django 3.0.6 on 2020-10-01 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20201001_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='outcome',
            field=models.CharField(default='未完成', max_length=255, verbose_name='产出'),
        ),
        migrations.AlterField(
            model_name='action',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='todo.Schedule', verbose_name='预约表'),
        ),
        migrations.AlterField(
            model_name='action',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='todo.Task', verbose_name='针对任务'),
        ),
    ]
