# Generated by Django 3.0.6 on 2020-05-13 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='status',
            new_name='is_active',
        ),
    ]
