# Generated by Django 3.0.6 on 2020-05-21 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realm', '0002_auto_20200514_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('upload_time', models.DateTimeField(verbose_name='time upload')),
                ('img_url', models.ImageField(blank=True, null=True, upload_to='realm/')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('publish_time', models.DateTimeField(verbose_name='time published')),
                ('content', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realm.User')),
            ],
        ),
    ]
