# Generated by Django 3.0.6 on 2020-05-21 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realm', '0003_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img_url',
            new_name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='md5_key',
            field=models.CharField(default=' ', max_length=36),
        ),
        migrations.AddField(
            model_name='image',
            name='upload_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realm.User'),
        ),
        migrations.AlterField(
            model_name='image',
            name='filename',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
