# Generated by Django 3.0.6 on 2020-05-24 07:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('realm', '0005_image_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 7, 7, 42, 970375, tzinfo=utc), verbose_name='time created'),
        ),
        migrations.AddField(
            model_name='article',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 7, 7, 42, 970375, tzinfo=utc), verbose_name='time updated'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realm.Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='time published'),
        ),
    ]
