# Generated by Django 3.0.6 on 2020-05-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realm', '0007_auto_20200524_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(1, 'Saved'), (2, 'Published')], default=1),
        ),
    ]
