# Generated by Django 3.0.6 on 2020-05-25 04:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('realm', '0008_article_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('comment', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time created')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time updated')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realm.User')),
            ],
        ),
    ]
