# Generated by Django 3.0.6 on 2020-05-30 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realm', '0010_article_column'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='url',
            new_name='image',
        ),
        migrations.AddField(
            model_name='column',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='is deleted'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realm.Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(1, 'Saved'), (2, 'Published'), (3, 'Removed')], default=1),
        ),
    ]
